### ISSUE TITLE
Implementar cache

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/backend#11]
Opções:
- Redis

**Comment by mfagundes** [comment]
A partir da versão 4, o Django passou a suportar nativamente o Redis ([docs](https://docs.djangoproject.com/en/4.1/topics/cache/#redis)). É necessário instalar o [redis.py](https://pypi.org/project/redis/)

A documentação do Django também recomenda o [hiredis](https://pypi.org/project/hiredis/), mas me pareceu que ele é desnecessário para o nosso caso.

De qualquer forma, me parece que é a melhor opção para o cache.
