### ISSUE TITLE
Melhorias no admin do Django

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/backend#110]
Para que a equipe de dados possa administrar os metadados no Django, estamos ajustando a interface para ficar mais amigável, enquanto não terminamos o frontend para o usuário. Alterações a serem feitas:

- [x] #165
- [x] #278
- [ ] ajustar para que a busca de observation_level na página de colunas só apareça observation_levels que existam na tabela daquela coluna
    `tabela` 1:1 `observation level` 1:muitos `entidades` 1:muitos `colunas`
    `tabela` 1:muitos `coluna`
- [x] Não aparecem opções de preencher diretórios de data_tempo na edição de coluna
- [x] #133
    - urgencia só no `raw_data_source`
- [x] O search do campo `cloud_table` não funciona
- [ ] ajustar busca de entidade (busca só funciona em português mesmo os nomes estando em inglês)
----
- [x] preencher o campo is_closed com true bloqueia mutations no dataset e suas tabelas via api, ver se podemos tirar essa validação (a coluna não pode ser aberta se o dataset é fechado)
- [x] #134
- [ ] exibir o `updates` em: `table`, `information_request`, `raw_data_source`
- [x] esconder informações desnecessárias na edição de coberturas
- [ ] incluir datatime range no Table Coverages
- [ ] #139
- [x] #141
- [x] #140
- [x] #131
- [x] #120

**Comment by vncsna** [comment]
Vale realizar futuros ajustes no django admin por demanda ou necessidade
