### ISSUE TITLE
Planejamento migração

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/backend#121]
Dia **BD**

Infraestrutura

- [x] Zerar o banco na sexta à tarde (@guialvesp1 )
- [x] Migração dos metadados - logo depois de zerar o banco - (@d116626 )
- [x] Migração imagens - (@mfagundes )
- [ ] Lançar nova versão pacote - (@lucascr91 )
- [ ] Alterar settings `ALLOWED_HOSTS` do Django - (@mfagundes @gabriel-milan @guialvesp1)
- [x] #136
- [x] Mudar o DNS do site - (@guialvesp1 )
- [ ] Refatorar as Actions (mais) - (@gabriel-milan )
- [ ] Mover imagens de temas para o bucket do GCS - (@mfagundes @AldemirLucas @guialvesp1 )
- [ ] Fazer backup e desligar instâncias (esperar time de dados validar migrações) - (@guialvesp1)

Frontend
- [x] Ajustar a query do BigQuery nas tabelas - @AldemirLucas 
- [ ] Cobertura temporal no dataset: a data final está igual à inicial - @AldemirLucas 
- [x] Faltam as informações adicionais nas tabelas - @AldemirLucas @mfagundes

**Comment by rdahis** [comment]
Podemos fechar?
