### ISSUE TITLE
Nova gestão de (meta)dados

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#125]
## Proposta atual

Versionamento tipo o Prefect.
* Criamos novas versões de objetos, que indicam `version`, `status=published`.
* No FE, só exibe objetos com `status=published`

- [x] #142
- [x] #143
- [x] #144

## A fazer

- [x] Estudar o Simple History. @mfagundes

**Comment by mfagundes** [comment]
Avaliei o [Django Simple History](https://github.com/jazzband/django-simple-history) e o [Django Reversion](https://github.com/etianen/django-reversion). Conversando com o @gabriel-milan chegamos à conclusão de que estas bibliotecas quebrariam o esquema do GraphQL

**Comment by vncsna** [comment]
@rdahis o objetivo é ter um histórico de alterações?

**Comment by rdahis** [comment]
Como funcionaria esse caminho de modelar o banco de produção e usar snapshots @vncsna?

**Comment by vncsna** [comment]
Se for a questão de ter backups de emergência, imagino que a instância do cloudsql já está configurada. Se for uma questão de ter histórico talvez dê pra copiar os dados de produção necessários para outro banco e usar [dbt snapshots](https://docs.getdbt.com/docs/build/snapshots) em um periodo mensal. Também existe a opção de mandar alguns dados pra um cloud storage
![image](https://github.com/basedosdados/backend/assets/4673693/9b390da0-d632-469e-87f4-8c9e58fa77ea)

**Comment by rdahis** [comment]
Não era isso não. A ideia, que chegamos a começar a desenvolver com João e cia, era de ter um versionamento de metadados para poder potencializar o sistema integrado de gestão de dados dentro da plataforma. Mas vamos deixar quieto por enquanto. Vai precisar de mais planejamento e mais braço quando formos implementar.
