### ISSUE TITLE
Ajustes pós-migração

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/backend#145]
Infraestrutura:
- [x] #148

Backend
- [x] #170
- [x] No dropdown de `column.directory_primary_key`, exibir só colunas que são `is_primary_key = True`
- [x] #166
- [x] #149
- [x] #165
- [x] #218
- [x] #250
- [x] #249
- [x] #150
- [x] #155
- [x] #158
- [ ] #167
- [ ] #174
- [ ] Validação do campo `column.measurement_unit` com componentes da string.
- [ ] Criar filtro de `spatial_coverage` igual ao do CKAN.
- [ ] #80

Frontend
- [x] #168
- [x] #151
- [ ] #152
- [x] #154
- [ ] Incluir filtros na tabela de arquitetura
- [x] Atualizar repositório `website` para ser só frontend.

Pacote
- [x] #153
- [x] #156

Dados
- [ ] Migrar tudo em `mais/bases/*/code` para o repositório de DBT (e refazer links onde isso aparecer downstream)

**Comment by vncsna** [comment]
Vale realizar futuros ajustes no django admin por demanda ou necessidade²
