### ISSUE TITLE
Suporte para ordem de colunas

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#165]
### Problema

As colunas estão sendo exibidas em ordem alfabética, e não na ordem do BQ/DBT.

Exemplo: https://basedosdados.org/dataset/9a2368e4-2fa6-4b42-88b7-026aa048f5ab?table=82e257d0-3564-4122-ba4a-78a039ca89b7

### Solução

~~- [ ] Criar metadado `column.before` e `column.after` (como FK para `column`) @rdahis~~
~~- [ ] Criar mecânica desse metadado: criação, sincronização com BQ/DBT @laura-l-amaral~~
~~- [ ] Exibir colunas ordenadas no FE @AldemirLucas~~
~~- [ ] Ajustar formulário pra preencher campos quando rodar um `table create`~~
- [x] Instalar lib `django-ordered-model`
- [x] Alterar modelos para herdar do pacote
- [x] Alterar admin para incluir recursos de reordenamento
- [x] Rodar o comando `python manage.py reorder_model v1.Column

**Comment by mfagundes** [comment]
Analisando os recursos do Django e algumas libraries, concluí que o ideal é usarmos este [recurso do Django](https://docs.djangoproject.com/en/4.2/ref/models/options/#order-with-respect-to).

Esta [biblioteca](https://github.com/django-ordered-model/django-ordered-model) implementa este recurso, bem como `signals` para as atualizações pelo admin do Django. Vou testá-la e, se a utilizarmos, o ideal é que o pacote seja compatibilizado com ela.

**Comment by rdahis** [comment]
Solução bem mais apropriada do que os meus `before` e `after` inventados rs
