### ISSUE TITLE
[Discovery] Formulários

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#168]
Requerimentos

* Formulários (em ordem de prioridade)
  - [x] #270
  - [ ] #274
    - column
  - [ ] `information_request`
  - [ ] `raw_data_source`
  - [ ] `organization`
  - [ ] `dictionary` / `key`
  - [ ] `theme`
  - [ ] `tag`
  - [ ] `analysis`
  - [ ] `quality_check`

UX
* Dropdown de opções do campo (via Enum)
* Campos ManyToMany permitir seleção múltipla
* Modularizar informações detalhada de coluna para outra página
* Exibir campos "query reversa" e permitir adicionar novos
  * `coverage`
  * `update`
  * `observation_level`

**Comment by vncsna** [comment]
@AldemirLucas pode reabrir no frontend se for priorizada
