### ISSUE TITLE
Search retorna vazio para palavras com acento e palavras incompletas

### ISSUE THREAD

**Issue by lucascr91** [basedosdados/backend#169]
Para reproduzir o problema, basta pesquisar termos como "educacao"ou "educa" na pesquisa do site.

**Comment by mfagundes** [comment]
Esse problema foi parcialmente resolvido com a inclusão do `haystack_ngram`, conforme o PR #175 . Porém ainda é necessário fazer algumas melhorias, como o @rdahis apontou.

@lucascr91 não seria melhor fechar essa issue e reorganizar nas issues de melhoria, conforme #145

**Comment by rdahis** [comment]
Já resolvido em prod.
