### ISSUE TITLE
Dar rollback no `RELAY_CONNECTION_MAX_LIMIT`

### ISSUE THREAD

**Issue by gabriel-milan** [basedosdados/backend#173]
Modificamos o `RELAY_CONNECTION_MAX_LIMIT` para 1500 para, temporariamente, atender às demandas do site. Posteriormente, será necessário implementar paginação em todos os lugares e, enfim, voltar ao valor original (100).

**Comment by mfagundes** [comment]
@gabriel-milan a paginação está sendo feita pelo próprio Elasticsearch. Isso já pode ser alterado e fechado? Não sei se impactaria na indexação pois ainda preciso fazer indexações manuais devido ao fato de que os campos relacionados (como `contains_closed_tables`) não estarem sendo automaticamente atualizados pelo `django-haystack`

**Comment by vncsna** [comment]
Entendo a necessidade de paginação, mas não pareceu tão crítico até então
