### ISSUE TITLE
Refinamento da busca

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/backend#247]
A busca está sendo feita diretamente no Elasticsearch, que é reindexado automaticamente quando algum dataset é atualizado pelo `django-haystack`. Porém, algumas propriedades importantes para filtragem, como `contains_closed_tables`, `n_tables` etc não são atualizadas, uma vez que refletem o estado no momento em que o índice é criado. Além disso, as imagens são indexadas com um link que contém um hash que expira a cada 7 dias, o que demanda uma indexação semanal ou a busca de cada imagem no banco para exibição.

- [x] os dados relacionados sejam indexados
- [x] as imagens possuam sempre um link válido, independente de reindexação

As tasks anteriores já foram feitas em outras issues. Alterando para centralizarmos aqui as melhorias necessárias para o algoritmo de busca.

**Comment by laura-l-amaral** [comment]
Oi maurício, acho que podemos concentrar as mudanças na busca por aqui o que acha? 
Por algum motivo ele não está priorizando conjuntos com tabelas tratadas, quando a gente busca 'futebol' o conjunto tratado é o 6 a aparecer 

![image](https://github.com/basedosdados/backend/assets/100051996/7612e221-a3ad-4b5e-91eb-ae479cf15d2f)

**Comment by mfagundes** [comment]
Vou te pedir um favor: observe que a descrição do dataset Copa do Mundo Fifa de Futebol Feminino (https://basedosdados.org/dataset/ee4a450d-f3ca-4d77-993b-10ea798b8508?table=6b49abb1-f0c3-4033-9983-dc5d21cc64c5 <https://basedosdados.org/dataset/ee4a450d-f3ca-4d77-993b-10ea798b8508?table=6b49abb1-f0c3-4033-9983-dc5d21cc64c5>) não contém a palavra "futebol". Você pode editar incluindo este termo?

Está:
"A Copa do Mundo Feminina da FIFA acontece a cada quatro anos e conta com a participação de 32 nações competindo em âmbito internacional. Coletamos informações do site oficial da FIFA sobre cada partida disputada."

Mudar para (ou algo parecido, que inclua o termo futebol):
"A Copa do Mundo de Futebol Feminino da FIFA acontece a cada quatro anos e conta com a participação de 32 nações competindo em âmbito internacional. Coletamos informações do site oficial da FIFA sobre cada partida disputada."

Só para eu dar uma olhada antes de mudar qualquer coisa.

Mauricio Fagundes

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=bWF1cmljaW8uZmFndW5kZXNAZ21haWwuY29t>

On Wed Jul 26, 2023, 07:44 PM GMT, Laura Amaral ***@***.***> wrote:
> Oi maurício, acho que podemos concentrar as mudanças na busca por aqui o que acha?
> Por algum motivo ele não está priorizando conjuntos com tabelas tratadas, quando a gente busca 'futebol' o conjunto tratado é o 6 a aparecer
[image] <https://user-images.githubusercontent.com/100051996/256346598-7612e221-a3ad-4b5e-91eb-ae479cf15d2f.png>

**Comment by laura-l-amaral** [comment]
Feito! @mfagundes

**Comment by laura-l-amaral** [comment]
[Comentário da Fernanda no Discord](https://discordapp.com/channels/787841210433536010/1121521501296939129/1135158216469270540):
Amores, retomando rápido aqui: qual o algoritmo que estamos usando para ranqueamento? 

Ex: "Censo" retorna primeiro Nomes no Brasil, Censo Agropecuario e depois Censo Demográfico https://basedosdados.org/dataset?q=censo&datasets_with=open_tables&page=1

**Comment by laura-l-amaral** [comment]
Outro ponto aqui, quando eu busco CEP não aparece o conjunto de diretórios brasileiros, mesmo ele estando no nome da tabela. Vou mudar a descrição do conjunto pra resolver essa questão dessa tabela, mas acho que seria importante que o nome da tabela tbm estivesse relacionado ao campo de busca 
![image](https://github.com/basedosdados/backend/assets/100051996/ae79b507-12e4-4e4f-a31f-363f35ad72f3)

**Comment by vncsna** [comment]
@laura-l-amaral vou dar uma olhada nisso nesse pr https://github.com/basedosdados/backend/pull/543
