### ISSUE TITLE
Criar metadado para indicar cobertura diferente entre BDPro e BD+

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/backend#266]
Como a cobertura temporal já é uma entidade separada da tabela, pensei em permitir mais de uma cobertura temporal para cada tabela (tabela 1:n cobertura temporal), e incluir um atributo que indique se a cobertura é BD+ ou BDPro. Aí poderiamos separar as 2 coberturas, uma BD+ e outra BDPro pra mesma tabela

**Comment by rdahis** [comment]
I'm on it. Estou pensando na melhor modelagem aqui.

**Comment by rdahis** [comment]
@mfagundes 

1. add coverage.is_closed
2. kill dataset.is_closed, table.is_closed. manter column.is_closed.
3. validação pra coverage ser partição: cobre tudo, sem interseção
    - fun(coverage1, coverage2) -> TRUE if tem interseção
        - datetime_range:
	    - passar cobertura para datetime
	    - ver se lim_inf < lim_sup
	- area:
	    - pro futuro. hoje retorna TRUE
    - fun(coverage, type=(INT, datetime)) -> lista de cobertura (ex: [2001, 2002, 2003, 2004, ..., 2020])

**Comment by mfagundes** [comment]
Esta issue é complementada pela #281. Testar e fechar ambas.
