### ISSUE TITLE
`dataset`

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/backend#270]
- [x] Criação
- [x] Edição
- [x] Remoção

**Comment by AldemirLucas** [comment]
Selector de themes e tags funcional, faltando so ajustar o Organization para finalizar a etapa de criação de Dataset

![image](https://github.com/basedosdados/backend/assets/82185307/65e3173a-b88f-4220-84b6-0be2fa6f4873)

**Comment by AldemirLucas** [comment]
Apos se logar com um user que tem isAdmin
e ir na pagina de dados e clickar nesse botão
![image](https://github.com/basedosdados/backend/assets/82185307/345cd774-c379-4d7f-b2b7-2dbad843ffc8)
sera direcionado para a pagina de criação de datasets

**Comment by crislanealves** [comment]
🚀

**Comment by AldemirLucas** [comment]
Concluído a etapa de atualizacao(edição) de um dataset

basta passa o id do dataset:
`/dataset/control?dataset=45738ad1-80bb-4859-b685-26963f4b76a1`

![image](https://github.com/basedosdados/backend/assets/82185307/f97954db-9371-4fa7-99f7-8f500d1ee554)

**Comment by crislanealves** [comment]
@AldemirLucas podemos fechar aqui? O que falta exatamente?

**Comment by AldemirLucas** [comment]
![image](https://github.com/basedosdados/backend/assets/82185307/2b36d118-bddc-40a4-9b72-edff574f82d4)

Delete funcional, ele deleta dos os filhos acoplados ao dataset, issue concluída
