### ISSUE TITLE
`table`

### ISSUE THREAD

**Issue by AldemirLucas** [basedosdados/backend#274]
- [x] add
- [x] edit
 - [x] remove
 
 #### Campos para adicionar em table
- [ ] Cloud Tables
- [ ] Coverages
- [ ] DateTime Ranges
- [ ] Observation Level
- [ ] Updates
 
## Column

- [ ] add
  - [ ] tabela de arquitetura (excelzão, upload de csv, link sheets)
- [ ] edit
- [ ] remove

**Comment by crislanealves** [comment]
Transferido para o Jira.

S: 30-31.

**Comment by crislanealves** [comment]
card: https://basedosdados.atlassian.net/browse/EQP-21

**Comment by crislanealves** [comment]
https://basedosdados.atlassian.net/browse/EQP-21

**Comment by vncsna** [comment]
@AldemirLucas pode mover para o frontend
