### ISSUE TITLE
Busca com novas coberturas

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/backend#281]
[EQP-51](https://basedosdados.atlassian.net/browse/EQP-51)

Com a alteração das coberturas (`coverage`), devemos ter, na busca, as seguintes agregações:

- Tabelas tratadas, não mais com a separação BD Pro e BD+ (`datasets_with=tables`)
- Fontes originais (`datasets_with=raw_data_source`)
- Pedidos LAI (`datasets_with=information_requests`)
- Dados PRO, usando a property `contains_closed_data` (`datasets_with=closed_data`)

#266 

[EQP-51]: https://basedosdados.atlassian.net/browse/EQP-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rdahis** [comment]
Gostaria de mudar:
- `datasets_with=tables` -> `contains_tables`
- `datasets_with=raw_data_source` -> `contains_raw_data_sources`
- `datasets_with=information_requests` -> `contains_ information_requests`
- `datasets_with=closed_data` -> `contains_closed_data`

**Comment by rdahis** [comment]
Temos um JIRA também? Por que?

**Comment by crislanealves** [comment]
> Gostaria de mudar:
> 
> * `datasets_with=tables` -> `contains_tables`
> * `datasets_with=raw_data_source` -> `contains_raw_data_sources`
> * `datasets_with=information_requests` -> `contains_ information_requests`
> * `datasets_with=closed_data` -> `contains_closed_data`

A proposito @mfagundes e @rdahis  já tínhamos fechado a data de entrega dessa atividade. Isso é uma mudança de impacto ou só é semântica? @mfagundes vai querer manter a data? Lembra que o @AldemirLucas precisa disso para tocar a parte dele.

**Comment by mfagundes** [comment]
> > Gostaria de mudar:
> > 
> > * `datasets_with=tables` -> `contains_tables`
> > * `datasets_with=raw_data_source` -> `contains_raw_data_sources`
> > * `datasets_with=information_requests` -> `contains_ information_requests`
> > * `datasets_with=closed_data` -> `contains_closed_data`
> 
> A proposito @mfagundes e @rdahis já tínhamos fechado a data de entrega dessa atividade. Isso é uma mudança de impacto ou só é semântica? @mfagundes vai querer manter a data? Lembra que o @AldemirLucas precisa disso para tocar a parte dele.

Sim, apenas semântica e não precisa mudar data.

**Comment by mfagundes** [comment]
@AldemirLucas subi para development. Veja lá se está tudo ok e o que precisa para atualizar o front. Mantive as antigas query strings, para não quebrar. Mas incluí a opção `datasets_with=closed_data`. Fechei a coverage de adh para testar:

https://development.basedosdados.org/dataset?q=&datasets_with=closed_data

Não cheguei a testar o GraphQL.
