### ISSUE TITLE
Transformar campo `dataset.organization` em `ManyToMany`

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/backend#371]
Terá implicações para o `search` e para filtros.

Passos:
1. Criar campo auxiliar
2. Migrar organization para o novo campo.
3. Deletar campo organization.
4. Renomear campo auxiliar para organization.

**Comment by laura-l-amaral** [comment]
Como não é prioridade no momento, fechando a issue para organizar o backlog de backend
