### ISSUE TITLE
Criar campo column.original_names

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/backend#374]
`column.original_names` será ligado com um novo modelo class `columnOriginalName`.

Esse class `columnOriginalName` terá atributos: `column_id`, `coverage`, `value`.

Depois deverá ser incorporado ao:
1. Processo de subida de metadados de coluna; e, 
2. Ao FE, nos metadados de coluna na página de table.

Link Jira: [EQP-88](https://equipeplataforma.atlassian.net/browse/EQP-88)

[EQP-88]: https://equipeplataforma.atlassian.net/browse/EQP-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vncsna** [comment]
Foi concluido faz um tempo
