### ISSUE TITLE
Revisar e melhorar dependências do pacote `basedosdados`

### ISSUE THREAD

**Issue by crislanealves** [basedosdados/backend#376]
**Link do Jira**: [EQP-117](https://equipeplataforma.atlassian.net/browse/EQP-117)

[EQP-117]: https://equipeplataforma.atlassian.net/browse/EQP-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by vncsna** [comment]
@crislanealves posso fechar?

**Comment by crislanealves** [comment]
> @crislanealves posso fechar?

Yes!
