### ISSUE TITLE
[BUG] Busca "Recursos grátis" incluir tabelas BD Pro que tenham alguma cobertura aberta

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#383]
Link do Jira: [EQP-101](https://equipeplataforma.atlassian.net/browse/EQP-101)

Exemplo: https://basedosdados.org/dataset?q=&contains=tables&contains=open_data 

O filtro `contains=open_data` tem que retornar também os conjuntos que tenham tabelas BD Pro com alguma cobertura aberta. Hoje está sendo excluído.

[EQP-101]: https://equipeplataforma.atlassian.net/browse/EQP-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by laura-l-amaral** [comment]
Já resolvido

**Comment by rdahis** [comment]
Não tinha nem visto que foi resolvido. Maravilha.
