### ISSUE TITLE
Modelar Banco de Dados

### ISSUE THREAD

**Issue by JoaoCarabetta** [basedosdados/backend#5]

**Comment by guialvesp1** [comment]
Criado o repositório `docs` onde tem como objetivo armazenar toda a documentação da BD. A modelagem do banco de dados já estava bem avançada devido a colaboração em conjunto com o @rdahis. 

A documentação do banco está disponível em: https://github.com/basedosdados/docs/blob/main/docs/projects/backend/index.md

Após rever o vídeo do último encontro do assunto, temos estes pontos para validar:

1. [ ] "Como versionar um registro de uma tabela?" 

    > Penso que podemos ter uma entidade (tabela) Auditoria, onde terá os atributos como por exemplo: user, data, tipo de operação, objeto antes da modificação  e objeto pós modificação (esses objetos sendo do tipo json field). E através de signals vc faz uma operação  nessa tabela de auditoria e segue com a operação do objeto

2. [ ] "Como traduzir os dados e aplicação?" 

    > Aqui vejo que seja necessário mapear todos os campos e seus labels, mas acho bem mais interessante testar isso aqui 

3. [ ] (Futuro) "Integração da API da BD com os outros serviços core utilizados (GCP; GitHub; Prefect; etc)"

Também é necessário a validação das entidades que envolvem a gerencia de usuários e grupos.
