### ISSUE TITLE
Podemos matar os campos `name`, `description`, etc do banco quando for ter tradução?

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#50]
Se entendi certo, para campos traduzidos em várias línguas, o campo `name` no banco é desnecessário. Certo? É pra ter só o `slug`, que será lido pelo framework de tradução (onde lá sim estarão os campos `namePt`, `nameEn`, etc).

Caso sim, é preciso limpar os campos `name`, `description`, e qualquer outro que será traduzido, dos atuais modelos.

**Comment by mfagundes** [comment]
Não, de fato é o inverso. No modelo do Django o único campo que existe é o `name`. As variações de língua são criadas pelo `modeltranslation` no banco, seguindo o indicado em `translations.py`. Como português é a língua default o dado inserido no campo `name` é replicado em `namePt`. As demais línguas ficam em branco e devem ser preenchidas.

Não tenho certeza, mas acho que há uma opção de `AUTO_POPULATE` que permite que todos os campos sejam preenchidos automaticamente com a versão padrão. Ou seja, se não for manualmente traduzido irá retornar o conteúdo da língua default.

**Comment by rdahis** [comment]
Esse preenchimento vai acontecer onde? No banco? No front-end? Pode me mostrar um exemplo já feito para nós podermos começar a popular?

**Comment by guialvesp1** [comment]
> Esse preenchimento vai acontecer onde? No banco? No front-end? Pode me mostrar um exemplo já feito para nós podermos começar a popular?

Esse preenchimento pode ocorrer diretamente em chamadas contra a API ou via interface do [Django Admin](https://staging.api.basedosdados.org/admin/v1/dataset/add/) até termos o formulário personalizado no frontend.

**Comment by rdahis** [comment]
Esclarecido. Fechando o issue.
