### ISSUE TITLE
Permissionamento de usuários

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#53]
Contas podem pertencer a (1) organizações e/ou (2) grupos da BD. E podem participar de planos de assinatura.

1. organizações (Petrobrás, BD, etc.)
2. grupos BD (Dados, Plataforma, Comunicação, etc)

Dados (dataset/table/column/row) no datalake podem ser abertos ou fechados. Para dados fechados, é preciso ter permissão de leitura. Pode haver permissão com atraso (second/minute/hour/day/etc)

`group`: assinantes premium, assinantes Lemann
`role`: plano 1, plano 2, plano 3
`permission`: par de dado + atraso (ambos podem ser nulos)

plano é um conjunto de permissões

account : FK plano

Assinaturas em grupo
Assinaturas podem ser em grupo. Ex: Lemann contrata acesso para todas pessoas com email da Lemann.
Exigiremos uma conta na BD para pessoa ter acesso à assinatura.

### Estrutura/Fluxo

* permissões user (para accounts novas)
    * viewer de dados abertos
    * sugerir edições de dados

* permissões equipe_dados-analista
    * user +
    * aprovar edições de (meta)dados

* permissões de gerente de equipe
    * editar cargos da sua equipe na sua organização

* permissões de RH
    * editar cargos de todas equipes na sua organização

* permissões admin
    * editar usuários da sua organização/equipe_BD

---

Cada admin vê seus usuários abaixo.

---

Editando usuários abstratos inicialmente no PR #45.

**Comment by mfagundes** [comment]
- [ ] Criar página de login de usuários no Django (precisa ajustar no nginx)
- [ ] Colocar um reset de senha, com envio de email
- [ ] Criar página de registro de usuário, com email de confirmação
- [ ] Proteger com captcha
- [ ] Incluir os dados que existem no CKAN no modelo de usuários
- [ ] Subir as imagens existentes e salvar a url no modelo
- [ ] Manter a compatibilidade com o Gravatar?

**Comment by laura-l-amaral** [comment]
@rdahis essa issue parece ter sido essencialmente resolvida, posso fechar?
