### ISSUE TITLE
Permitir uso de markdown nos campos da plataforma.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#54]
No banco guardamos como `charField`, mas no FE entra como markdown.

Features:
* Ter visão de "preview" como no GitHub. (ver via admin de Django @mfagundes)

**Comment by mfagundes** [comment]
Este plugin parece que nos atende:

https://github.com/agusmakmun/django-markdown-editor

Vefiriquei e vi que ele é um projeto ativo e compatível com a versão atual do Django (4.1)
