### ISSUE TITLE
Checar qual foi o erro no django da semana passada

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/backend#572]

**Comment by vncsna** [comment]
O erro foi bem genérico, em que a conexão do banco quebrou durante o processo de geração do index, vide [logs](https://grafana.basedosdados.org/explore?orgId=1&left=%7B%22datasource%22:%22P8E80F9AEF21F6940%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P8E80F9AEF21F6940%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bapp%3D%5C%22api-prod%5C%22%7D%20%21~%20%5C%22elasticsearch%5C%22%20%21%3D%20%5C%22stripe%5C%22%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221709521200000%22,%22to%22:%221710212399000%22%7D%7D). Temos um task que deleta o index e cria novamente todo domingo e a conexão com o banco falhou no mesmo momento

**Comment by laura-l-amaral** [comment]
Beleza, então podemos seguir colocando esse retry mesmo!

**Comment by vncsna** [comment]
[PTAL](https://github.com/basedosdados/backend/pull/575)?
