### ISSUE TITLE
Limpar `slug` em: `organization` e `dataset`.

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#60]
* Em `organization`, remover os prefixos de `area`.
    * Exemplo: `br_inep` para `inep`.
    * Exemplo: `world_banco_mundial` para `banco_mundial`.
* Em `dataset`, remover os prefixos de `area` e `organization`.
    * Exemplo: `br_inep_censo_escolar` para `censo_escolar`.

Depois ajustar no front-end para pegar os campos `organization.slug` e `organization.area` para completar as exibições. @AldemirLucas

**Comment by mfagundes** [comment]
@rdahis Isso não vai quebrar a integração com o BigQuery?

**Comment by rdahis** [comment]
> @rdahis Isso não vai quebrar a integração com o BigQuery?

Hm... vamos ter que mudar o pacote para ajustar o passo de criar o nome do dataset e table no BQ mesmo.

**Comment by rdahis** [comment]
Não sei se isso é verdade. Vamos relacionar tudo via os novos `id`'s. @d116626
