### ISSUE TITLE
Reduzir o as informações retornadas para aqueles não autenticados no graphql. Para a query allSubscription

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/backend#618]
* Checar com matheus integração com o coda https://coda.io/d/Plataforma_dkbq8r9l4IO/Stripe-info_suMTR#_luion

![Image](https://github.com/basedosdados/backend/assets/5381250/eff6694f-0625-4954-9f8e-1f2cd7f9d833)

**Comment by jhonylucas74** [comment]
PR com a correção.
https://github.com/basedosdados/backend/pull/624
