### ISSUE TITLE
Levar dados de produção para o banco de desenvolvimento

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/backend#630]
- Otimizar o código que já existe
- Avaliar se puxa via metabase ou direto ao banco de produção
---
script de população
- [x] Dificuldade em remover tabelas por conta das conexões
- [x] Criação em camadas 

Próximos passos
- [x] fazer com que o django rode "automaticamente" 
- [x] contruir novo modelo para conseguir acompanhar o resultado das cron
- [x] automatizar o download do banco pelo metabase

Ajustes:
- [x] Avaliar se tem um limite de download e aumentar (problema nas colunas)
- [x] As tabelas que faziam relações entre modelos não estavam sendo migradas 
- [ ] Data de cobertura temporal ficou diferente na tabela de microdados do [conjunto da ANP de preços ](https://staging.basedosdados.org/dataset/6ea3e28a-42be-401a-a066-ad87ca931e69?table=3a7cb29a-0bdf-4f44-bab1-d27872e565ff)

**Comment by rdahis** [comment]
@jhonylucas74 pode por favor passar uma atualização dessa tarefa? Será que fica pronta até amanhã (terça)?
