### ISSUE TITLE
Implementar cupons

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/backend#658]
Implementação de descontos no momento do checkout.

**Comment by jhonylucas74** [comment]
@AldemirLucas Agora temos dois novos campos na hora de validar o cupom.

![Image](https://github.com/user-attachments/assets/a066c3f3-f939-497b-96b4-800ed5dc204f)

Basta incluir esses dois novos campos na mutation.

O campo duration será retornado como uma string com três possíveis valores:

- `forever`: O cupom será aplicado permanentemente na assinatura.
- `once`: O cupom será aplicado apenas na primeira cobrança.
- `repeating`: O cupom será aplicado por um período limitado. Verifique o campo durationInMonths para saber exatamente por quanto tempo o desconto será válido.
