### ISSUE TITLE
Erro ao acessar o django admin, está fazendo o servidor cair ao acessar elementos relacionados á  coverage e datetimerange.

### ISSUE THREAD

**Issue by jhonylucas74** [basedosdados/backend#668]
Gostaria de notificar que faz uns dias que a @equipe_dados  não consegue acessar elementos relacionados a coverage e nem datetimerange no backend.

Sempre que tento a pagina fica a carregando até tomar um 504 Gateway Time-out
Estamos contornando a situação fazendo querys pelo graphql. Mas acredito que seria bom investigar a causa desses timeouts

**Comment by rdahis** [comment]
Resolvido nesse commit: https://github.com/basedosdados/backend/commit/b62352443a3bea4486dfd926dd9e9d58abf95d92
