### ISSUE TITLE
Ajustar para que o campo de unit conecte com mais de uma coluna

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/backend#675]
O campo de unit criado nesse PR https://github.com/basedosdados/backend/pull/627 não satisfez a necessidade que tinhamos.

Um date time range pode conectar com uma única colunna como `data_referencia` ou mais de uma coluna, como `ano_referencia`e `mes_referencia`

A forma como foi feito permite apenas a conexão entre uma única coluna com o date time range

- [ ] Permitir múltiplas colunas.
- [ ] Atrelar a entidade representada pela coluna (via diretório)

**Comment by rdahis** [comment]
Qual é a urgência +/-?

**Comment by laura-l-amaral** [comment]
Isso atrapalha bastante a equipe dados, mas já estamos lidando sem. 

O impacto é que toda vez que rodamos uma nova atualização temos que lembrar de mudar na mão o datetimerange e as vezes esquecemos ou temos algum erro no processo, por isso os dados as vezes ficam desatualizados no site

Não colocaria na caixa de urgente, mas de importante. Em importancia eu colocaria bastante
