### ISSUE TITLE
Ajustes no django admin

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/backend#678]
* [x] não é possível abrir nenhum datetimerange sem que de erro no servidor
* [x] tentei adicionar uma cloud table aqui e deu erro de servidor https://backend.basedosdados.org/admin/v1/table/3fcc4082-700c-479c-8f89-66225982832a/change/#cloud-tables-tab

**Comment by rdahis** [comment]
Parte de `datetime_range` está resolvida em https://github.com/basedosdados/backend/commit/b62352443a3bea4486dfd926dd9e9d58abf95d92.

**Comment by rdahis** [comment]
Consertado a criação de `CloudTable` via aba em `Table`. Aqui: https://github.com/basedosdados/backend/commit/2da1b69ecdd0c3c49785bd7207c32902579d8ccd
