### ISSUE TITLE
Ver se `mutation` no GraphiQL está aberto para qualquer usuário ou não

### ISSUE THREAD

**Issue by rdahis** [basedosdados/backend#73]
Solução é  botar decorators?

**Comment by mfagundes** [comment]
Decorei a função apenas com `is_staff_member`. Com isso, apenas quem tiver esse status pode rodar mutations. Por ora é o suficiente, mas com a entrada dos usuários de fora da BD, que terão que ter permissões específicas, isso terá que ser repensado.
