### ISSUE TITLE
Bloquear acesso externo ao Elasticsearch

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/backend#84]
O Elasticsearch, por padrão, não incorpora segurança de acesso aos dados, o que permite que qualquer pessoa insira um resultado de busca lá. Isso precisa ser fechado, através de login para acesso à API e, preferencialmente, que apenas a aplicação tenha poder de escrita (via restrições de segurança)

**Comment by lucascr91** [comment]
@guialvesp1 qual a pertinência dessa issue atualmente? Existe necessidade de realizar o bloqueio do ES, dado que a aplicação está deployada no cluster?
