### ISSUE TITLE
Registro de usuário, com envio de email

### ISSUE THREAD

**Issue by mfagundes** [basedosdados/backend#94]
Fazer um form para registro de novos usuários e enviar email para confirmação. O usuário ficará inativado e só ativará após o registro final

**Comment by mfagundes** [comment]
Para reduzir o tamanho das issues, vou separar o captcha em outra issue

**Comment by mfagundes** [comment]
Closes #95

**Comment by rdahis** [comment]
Pode fechar essas issues agora? Parece que já está em staging.

**Comment by rdahis** [comment]
Podemos fechar? @mfagundes
